export const APPLICATION_AUDIT_EVENTS = [
  "APPLICATION_CREATED",
  "APPLICATION_SUBMITTED",
  "APPLICATION_REVIEW_STARTED",
  "APPLICATION_RESUBMITTED",
  "APPLICATION_AMENDMENT_ACKNOWLEDGED",
  "APPLICATION_AMENDMENTS_REQUESTED",
  "APPLICATION_REOPENED_FOR_REVIEW",
  "APPLICATION_WITHDRAWN",
  "APPLICATION_REJECTED",
  "APPLICATION_ARCHIVED",
  "APPLICATION_DRAFT_DELETED",
  "APPLICATION_COMPLETED",
  "APPLICATION_SECTION_REVIEW_UPDATED",
  "APPLICATION_ITEM_REVIEW_UPDATED",
  "APPLICATION_DOCUMENT_UPLOADED",
  "APPLICATION_DOCUMENT_REMOVED",
  "APPLICATION_DOCUMENT_REPLACED",
  "CONTRACT_OFFER_SENT",
  "CONTRACT_OFFER_RETRACTED",
  "CONTRACT_SIGNING_DEADLINE_EXTENDED",
  "CONTRACT_OFFER_EXPIRED",
  "CONTRACT_ACCEPTANCE_SUBMITTED",
  "CONTRACT_ACCEPTANCE_RESUBMITTED",
  "CONTRACT_ACCEPTANCE_CHANGES_REQUESTED",
  "CONTRACT_ACCEPTANCE_APPROVED_FOR_SIGNING",
  "CONTRACT_OFFER_ACCEPTED",
  "CONTRACT_OFFER_REJECTED",
  "CONTRACT_WITHDRAWN",
  "CONTRACT_CUSTOMER_LARGE_PRIVATE_UPDATED",
  "INVOICE_OFFER_SENT",
  "INVOICE_OFFER_RETRACTED",
  "INVOICE_SIGNING_DEADLINE_EXTENDED",
  "INVOICE_OFFER_EXPIRED",
  "INVOICE_ACCEPTANCE_SUBMITTED",
  "INVOICE_ACCEPTANCE_RESUBMITTED",
  "INVOICE_ACCEPTANCE_CHANGES_REQUESTED",
  "INVOICE_ACCEPTANCE_APPROVED_FOR_SIGNING",
  "INVOICE_OFFER_ACCEPTED",
  "INVOICE_OFFER_REJECTED",
  "INVOICE_WITHDRAWN",
  "CONTRACT_FACILITY_OCCUPANCY_UPDATED",
] as const;

export type ApplicationAuditEventType = (typeof APPLICATION_AUDIT_EVENTS)[number];

export const APPLICATION_AUDIT_TARGET_TYPE = {
  APPLICATION: "APPLICATION",
  CONTRACT: "CONTRACT",
  INVOICE: "INVOICE",
  REVIEW_SECTION: "REVIEW_SECTION",
  REVIEW_ITEM: "REVIEW_ITEM",
  DOCUMENT: "DOCUMENT",
} as const;

export type ApplicationAuditTargetType =
  (typeof APPLICATION_AUDIT_TARGET_TYPE)[keyof typeof APPLICATION_AUDIT_TARGET_TYPE];

export const APPLICATION_OFFER_COMPLETION_METHOD = {
  DIRECT_ACCEPTANCE: "DIRECT_ACCEPTANCE",
  SIGNING_COMPLETION: "SIGNING_COMPLETION",
} as const;

export type ApplicationOfferCompletionMethod =
  (typeof APPLICATION_OFFER_COMPLETION_METHOD)[keyof typeof APPLICATION_OFFER_COMPLETION_METHOD];

export function isApplicationAuditEventType(value: string): value is ApplicationAuditEventType {
  return (APPLICATION_AUDIT_EVENTS as readonly string[]).includes(value);
}
