export const APPLICATION_ACTION_REQUIRED_STATUSES = [
  "SUBMITTED",
  "UNDER_REVIEW",
  "RESUBMITTED",
  "CONTRACT_PENDING",
  "CONTRACT_ACCEPTED",
  "INVOICE_PENDING",
] as const;

export const APPLICATION_ACTION_REQUIRED_STATUS_SET = new Set<string>(
  APPLICATION_ACTION_REQUIRED_STATUSES
);
