export const SECURITY_AUDIT_EVENTS = [
  "USER_ROLE_ADDED",
  "ACTIVE_ROLE_CHANGED",
  "USER_PROFILE_UPDATED",
  "USER_PROFILE_UPDATED_BY_ADMIN",
  "PASSWORD_CHANGED",
  "PASSWORD_CHANGE_FAILED",
  "USER_EMAIL_VERIFIED",
  "EMAIL_VERIFICATION_FAILED",
  "ADMIN_ACCESS_DENIED",
  "ADMIN_ROLE_CREATED",
  "ADMIN_ROLE_PERMISSIONS_UPDATED",
  "ADMIN_ROLE_DELETED",
  "USER_ROLES_UPDATED",
  "ADMIN_USER_ROLE_CHANGED",
  "ADMIN_USER_DEACTIVATED",
  "ADMIN_USER_REACTIVATED",
  "ADMIN_INVITATION_CREATED",
  "ADMIN_INVITATION_LINK_GENERATED",
  "ADMIN_INVITATION_RESENT",
  "ADMIN_INVITATION_REVOKED",
  "ADMIN_INVITATION_ACCEPTED",
  "USER_PUBLIC_ID_CHANGED",
  "ORGANIZATION_MEMBER_INVITED",
  "ORGANIZATION_MEMBER_JOINED",
  "ORGANIZATION_MEMBER_REMOVED",
  "ORGANIZATION_MEMBER_LEFT",
  "ORGANIZATION_MEMBER_ROLE_UPDATED",
  "ORGANIZATION_OWNERSHIP_TRANSFERRED",
  "ORGANIZATION_INVITATION_REVOKED",
  "ORGANIZATION_INVITATION_RESENT",
  "NOTIFICATION_TYPE_UPDATED",
  "NOTIFICATION_GROUP_CREATED",
  "NOTIFICATION_GROUP_UPDATED",
  "NOTIFICATION_GROUP_DELETED",
  "USER_NOTIFICATION_PREFERENCE_UPDATED",
] as const;

/** Historical event types with no current writer. IDs A004, A005, and A016 stay reserved. */
export const RETIRED_SECURITY_AUDIT_EVENTS = [
  "USER_ROLE_ADDED",
  "ACTIVE_ROLE_CHANGED",
  "USER_ROLES_UPDATED",
] as const;

export type SecurityAuditEventType = (typeof SECURITY_AUDIT_EVENTS)[number];

export const SECURITY_AUDIT_TARGET_TYPE = {
  USER: "USER",
  ADMIN_ROLE: "ADMIN_ROLE",
  ADMIN_INVITATION: "ADMIN_INVITATION",
  ORGANIZATION: "ORGANIZATION",
  ORGANIZATION_INVITATION: "ORGANIZATION_INVITATION",
  ORGANIZATION_MEMBER: "ORGANIZATION_MEMBER",
  NOTIFICATION_TYPE: "NOTIFICATION_TYPE",
  NOTIFICATION_GROUP: "NOTIFICATION_GROUP",
  USER_NOTIFICATION_PREFERENCE: "USER_NOTIFICATION_PREFERENCE",
  ADMIN_ROUTE: "ADMIN_ROUTE",
} as const;

export type SecurityAuditTargetType =
  (typeof SECURITY_AUDIT_TARGET_TYPE)[keyof typeof SECURITY_AUDIT_TARGET_TYPE];

export function isSecurityAuditEventType(value: string): value is SecurityAuditEventType {
  return (SECURITY_AUDIT_EVENTS as readonly string[]).includes(value);
}
