export const NOTE_AUDIT_EVENTS = [
  "NOTE_CREATED",
  "NOTE_TERMS_UPDATED",
  "NOTE_PROSPECTUS_REVIEW_CREATED",
  "NOTE_PROSPECTUS_APPROVED",
  "NOTE_PROSPECTUS_INVALIDATED",
  "NOTE_PUBLISHED",
  "NOTE_UNPUBLISHED",
  "INVESTMENT_COMMITTED",
  "NOTE_FUNDING_CLOSED",
  "NOTE_FUNDING_FAILED",
  "NOTE_ACTIVATED",
  "NOTE_SERVICING_STATUS_CHANGED",
  "NOTE_MARKED_DEFAULT",
  "DISBURSEMENT_INITIATED",
  "DISBURSEMENT_LETTER_GENERATED",
  "DISBURSEMENT_SUBMITTED_TO_TRUSTEE",
  "DISBURSEMENT_BENEFICIARY_UPDATED",
  "DISBURSEMENT_COMPLETED",
  "RESIDUAL_RETURN_LETTER_GENERATED",
  "RESIDUAL_RETURN_SUBMITTED_TO_TRUSTEE",
  "RESIDUAL_RETURN_COMPLETED",
  "SHORAKA_ORDER_SUBMITTED",
  "SHORAKA_CERTIFICATE_RECEIVED",
  "REPAYMENT_SUBMITTED",
  "REPAYMENT_RECEIVED",
  "REPAYMENT_REJECTED",
  "SETTLEMENT_PREVIEWED",
  "SETTLEMENT_APPROVED",
  "SETTLEMENT_POSTED",
  "SERVICE_FEE_TRUSTEE_LETTER_GENERATED",
  "SERVICE_FEE_TRUSTEE_SUBMITTED",
  "SERVICE_FEE_TRUSTEE_COMPLETED",
  "ARREARS_LETTER_GENERATED",
  "DEFAULT_NOTICE_GENERATED",
  "TRUSTEE_SIGNATURE_UPDATED",
] as const;

export type NoteAuditEventType = (typeof NOTE_AUDIT_EVENTS)[number];

export const NOTE_AUDIT_TARGET_TYPE = {
  NOTE: "NOTE",
  INVESTMENT: "INVESTMENT",
  NOTE_PAYMENT: "NOTE_PAYMENT",
  SETTLEMENT: "SETTLEMENT",
  WITHDRAWAL: "WITHDRAWAL",
  PUBLICATION: "PUBLICATION",
  REVIEW: "REVIEW",
  SHORAKA_ORDER: "SHORAKA_ORDER",
  PLATFORM_SETTING: "PLATFORM_SETTING",
} as const;

export type NoteAuditTargetType =
  (typeof NOTE_AUDIT_TARGET_TYPE)[keyof typeof NOTE_AUDIT_TARGET_TYPE];

export const NOTE_AUDIT_PROVIDER = "SHORAKA" as const;

export const NOTE_PROSPECTUS_INVALIDATION_REASON = {
  SOURCE_CHANGED: "SOURCE_CHANGED",
  EDIT_AFTER_APPROVAL: "EDIT_AFTER_APPROVAL",
} as const;

export type NoteProspectusInvalidationReason =
  (typeof NOTE_PROSPECTUS_INVALIDATION_REASON)[keyof typeof NOTE_PROSPECTUS_INVALIDATION_REASON];

export const NOTE_AUDIT_CURRENCY = "MYR" as const;

export function isNoteAuditEventType(value: string): value is NoteAuditEventType {
  return (NOTE_AUDIT_EVENTS as readonly string[]).includes(value);
}
