import {
  NotificationCategory,
  NotificationPortalTarget,
  NotificationPriority,
} from "@prisma/client";

const BOTH_PORTALS = [
  NotificationPortalTarget.INVESTOR,
  NotificationPortalTarget.ISSUER,
];
const ISSUER_ONLY = [NotificationPortalTarget.ISSUER];
const INVESTOR_ONLY = [NotificationPortalTarget.INVESTOR];

export const initialNotificationTypes = [
  // Authentication (always enabled, not user configurable)
  {
    id: "password_changed",
    name: "Password Changed",
    description: "Sent when your account password has been successfully changed.",
    category: NotificationCategory.AUTHENTICATION,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "login_new_device",
    name: "Login from New Device",
    description: "Sent when a login is detected from a device or location we don't recognize.",
    category: NotificationCategory.AUTHENTICATION,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },

  // System / Onboarding
  {
    id: "kyc_approved",
    name: "KYC Approved",
    description: "Sent when your identity verification has been approved.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "kyc_rejected",
    name: "KYC Rejected",
    description: "Sent when your identity verification has been rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "onboarding_approved",
    name: "Onboarding Approved",
    description: "Sent when your onboarding application has been approved.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "onboarding_rejected",
    name: "Onboarding Rejected",
    description: "Sent when your onboarding application has been rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },

  // Announcement
  {
    id: "system_announcement",
    name: "System Announcement",
    description: "General announcements about platform updates and maintenance.",
    category: NotificationCategory.ANNOUNCEMENT,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },

  // Marketing
  {
    id: "new_product_alert",
    name: "New Product Alert",
    description: "Be the first to know about new investment opportunities and products.",
    category: NotificationCategory.MARKETING,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  // Issuer application lifecycle
  {
    id: "application_amendments_requested",
    name: "Application Amendments Requested",
    description: "Sent when reviewers submit amendment requests on your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_approved",
    name: "Application Approved",
    description: "Sent when your application is approved.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_rejected",
    name: "Application Rejected",
    description: "Sent when your application is rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "contract_offer_sent",
    name: "Contract Offer Sent",
    description: "Sent when a contract offer is sent to your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "invoice_offer_sent",
    name: "Invoice Offer Sent",
    description: "Sent when an invoice offer is sent to your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "offer_retracted_or_reset",
    name: "Offer Retracted or Reset",
    description: "Sent when a previously sent offer is retracted or reset by reviewer action.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "offer_expired",
    name: "Offer Expired",
    description: "Sent when a contract or invoice offer expires.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "offer_expiry_reminder_24h",
    name: "Offer Expiry Reminder (24h)",
    description: "Reminder sent before an offer expires within 24 hours.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_resubmitted_confirmation",
    name: "Application Resubmitted Confirmation",
    description: "Confirmation sent after you resubmit your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "application_withdrawn_confirmation",
    name: "Application Withdrawn Confirmation",
    description: "Confirmation sent after you withdraw your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "application_completed",
    name: "Application Completed",
    description: "Sent when your application reaches completed status.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "director_shareholder_mismatch",
    name: "Directors/Shareholders Update Required",
    description:
      "Sent when your organization must complete director or shareholder verification (AML-driven).",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "director_shareholder_action_required",
    name: "Director/Shareholder Action Required",
    description: "Sent when admin requests onboarding action for a specific director/shareholder.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_published",
    name: "Note published",
    description: "Your note was published to the marketplace for funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_funding_succeeded",
    name: "Note funding succeeded",
    description: "Funding closed successfully for your note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_funding_failed_issuer",
    name: "Note funding failed",
    description: "A note listing did not reach the minimum funding threshold.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_funding_failed_investor",
    name: "Note funding failed",
    description: "Reserved commitment released because a note did not complete funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_active_issuer",
    name: "Note active",
    description: "Your note is active after funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_active_investor",
    name: "Note active",
    description: "A note you funded is active.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_repaid_issuer",
    name: "Note repaid",
    description: "Your note has been fully repaid and settled.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_payment_received",
    name: "Note repayment recorded",
    description: "A repayment was recorded on a note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_settlement_posted",
    name: "Note settlement posted",
    description: "Settlement posted for a note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_arrears",
    name: "Note in arrears",
    description: "A note entered arrears status.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_arrears_investor",
    name: "Note in arrears",
    description: "A note you invested in is in arrears.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_defaulted",
    name: "Note defaulted (issuer)",
    description: "A note was marked as default.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "note_defaulted_investor",
    name: "Note defaulted",
    description: "A note you invested in was marked as default.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "withdrawal_submitted_to_trustee",
    name: "Withdrawal submitted to trustee",
    description: "A withdrawal instruction was submitted to the trustee.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
];
