import {
  NotificationCategory,
  NotificationPortalTarget,
  NotificationPriority,
} from "@prisma/client";

const BOTH_PORTALS = [NotificationPortalTarget.INVESTOR, NotificationPortalTarget.ISSUER];
const ISSUER_ONLY = [NotificationPortalTarget.ISSUER];
const INVESTOR_ONLY = [NotificationPortalTarget.INVESTOR];

export const initialNotificationTypes = [
  // Authentication (always enabled, not user configurable)
  {
    id: "password_changed",
    name: "Password Changed",
    description: "Sent when your account password has been successfully changed.",
    category: NotificationCategory.AUTHENTICATION,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },

  // System / Onboarding
  {
    id: "onboarding_approved",
    name: "Onboarding Approved",
    description: "Sent when your onboarding application has been approved.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "onboarding_rejected",
    name: "Onboarding Rejected",
    description: "Sent when your onboarding application has been rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },

  // Announcement
  {
    id: "system_announcement",
    name: "System Announcement",
    description: "General announcements about platform updates and maintenance.",
    category: NotificationCategory.ANNOUNCEMENT,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },

  // Marketing
  {
    id: "new_product_alert",
    name: "New Product Alert",
    description: "Be the first to know about new investment opportunities and products.",
    category: NotificationCategory.MARKETING,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  // Issuer application lifecycle
  {
    id: "application_amendments_requested",
    name: "Application Amendments Requested",
    description: "Sent when reviewers submit amendment requests on your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "acceptance_document_changes_requested",
    name: "Acceptance Documents Need Updates",
    description:
      "Sent once when a reviewer first requests acceptance-document changes after offer submission (further requests in the same cycle do not re-notify).",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_rejected",
    name: "Application Rejected",
    description: "Sent when your application is rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "contract_offer_sent",
    name: "Facility Offer Sent",
    description: "Sent when a facility offer is sent to your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "invoice_offer_sent",
    name: "Invoice Offer Sent",
    description: "Sent when an invoice offer is sent to your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "offer_retracted_or_reset",
    name: "Offer Retracted or Reset",
    description: "Sent when a previously sent offer is retracted or reset by reviewer action.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "offer_expired",
    name: "Offer Expired",
    description: "Sent when a facility or invoice offer expires.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "offer_expiry_reminder_24h",
    name: "Offer Expiry Reminder",
    description:
      "Reminder sent before an acceptance or signing deadline (days_before_expiry from product config).",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_resubmitted_confirmation",
    name: "Application Resubmitted Confirmation",
    description: "Confirmation sent after you resubmit your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_withdrawn_confirmation",
    name: "Application Withdrawn Confirmation",
    description: "Confirmation sent after you withdraw your application.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_completed",
    name: "Application Completed",
    description: "Sent when your application reaches completed status.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "application_submitted_confirmation",
    name: "Application Submitted Confirmation",
    description: "Confirmation sent after you submit a new application for review.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "contract_signing_deadline_extended",
    name: "Facility Signing Deadline Extended",
    description: "Sent when the signing deadline for a facility offer is extended.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "invoice_signing_deadline_extended",
    name: "Invoice Signing Deadline Extended",
    description: "Sent when the signing deadline for an invoice offer is extended.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "facility_disabled",
    name: "Facility Disabled",
    description: "Sent when an admin disables a facility, blocking new drawdowns.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "director_shareholder_action_required",
    name: "Director/Shareholder Action Required",
    description:
      "Sent to the issuer organization owner when a CTOS pull finds new directors or shareholders who need onboarding action.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "investor_director_shareholder_action_required",
    name: "Investor Director/Shareholder Action Required",
    description:
      "Sent to the investor organization owner when a CTOS pull finds new directors or shareholders who need onboarding action.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: false,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_published",
    name: "Note published",
    description: "Your note was published to the marketplace for funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_funding_succeeded",
    name: "Note funding succeeded",
    description: "Funding closed successfully for your note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_funding_failed_issuer",
    name: "Note funding failed",
    description: "A note listing did not reach the minimum funding threshold.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_funding_failed_investor",
    name: "Note funding failed",
    description: "Reserved commitment released because a note did not complete funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_active_issuer",
    name: "Note active",
    description: "Your note is active after funding.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_active_investor",
    name: "Note active",
    description: "A note you funded is active.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_repaid_issuer",
    name: "Note repaid",
    description: "Your note has been fully repaid and settled.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_payment_received",
    name: "Note repayment recorded",
    description: "A repayment was recorded on a note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_settlement_posted",
    name: "Note settlement posted",
    description: "Settlement posted for a note.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_arrears",
    name: "Note in arrears",
    description: "A note entered arrears status.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_arrears_investor",
    name: "Note in arrears",
    description: "A note you invested in is in arrears.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_defaulted",
    name: "Note defaulted (issuer)",
    description: "A note was marked as default.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_defaulted_investor",
    name: "Note defaulted",
    description: "A note you invested in was marked as default.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.CRITICAL,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "withdrawal_submitted_to_trustee",
    name: "Withdrawal submitted to trustee",
    description: "A withdrawal instruction was submitted to the trustee.",
    category: NotificationCategory.SYSTEM,
    portal_targets: BOTH_PORTALS,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "note_payment_rejected",
    name: "Repayment rejected",
    description: "A repayment you submitted for a note was rejected.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "withdrawal_completed",
    name: "Disbursement completed",
    description: "Your note's financing disbursement has been completed.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "facility_fee_payment_requested",
    name: "Upfront facility fee payment required",
    description:
      "Sent after you accept a facility offer that requires an upfront facility fee gateway payment.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "facility_fee_upfront_paid",
    name: "Upfront facility fee paid",
    description: "Sent once when the upfront facility fee on a facility has been paid in full.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "excess_late_charges_due",
    name: "Outstanding late charges to pay",
    description:
      "Sent after a settlement is posted with late charges that did not fit into the repayment.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },
  {
    id: "excess_late_charges_paid",
    name: "Late payment charges received",
    description:
      "Sent once when separately collected late charges on a note have been paid in full.",
    category: NotificationCategory.SYSTEM,
    portal_targets: ISSUER_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: true,
  },

  // Investor gateway / deposit lifecycle
  {
    id: "deposit_name_check_rejected",
    name: "Deposit verification failed",
    description: "Sent when a deposit fails bank-name verification and will be returned.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.WARNING,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "deposit_refund_initiated",
    name: "Deposit refund started",
    description: "Sent when a refund for a deposit has been initiated.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
  {
    id: "deposit_refunded",
    name: "Deposit refund completed",
    description: "Sent when a deposit refund has been completed.",
    category: NotificationCategory.SYSTEM,
    portal_targets: INVESTOR_ONLY,
    default_priority: NotificationPriority.INFO,
    user_configurable: true,
    enabled_platform: true,
    enabled_email: false,
  },
];
