/**
 * Mock data for Applications dashboard when USE_MOCK_DATA is true.
 *
 * Each entry is NormalizedApplication (same shape as adapter output). Used when API is unavailable
 * or for local testing. Switch USE_MOCK_DATA to false to use GET /v1/applications.
 */

import type { NormalizedApplication } from "./status";

/* true = use mockApplications below. false = fetch from GET /v1/applications. */

export const USE_MOCK_DATA = false;

/* One NormalizedApplication per card. Add entries to test different statuses. */

export const mockApplications: NormalizedApplication[] = [
  /* Draft invoice financing — user chose invoice-only, has invoices in progress */
  {
    id: "mock-draft-inv-1",
    type: "Invoice financing",
    status: "draft",
    cardStatus: {
      badgeKey: "draft",
      displayLabel: "Draft",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: null,
    customer: "Acme Trading Sdn Bhd",
    applicationDate: "2026-03-10",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-10T10:00:00Z",
    invoices: [
      {
        id: "inv-mock-1",
        number: "INV-001",
        maturityDate: "2026-04-15",
        value: 50000,
        appliedFinancing: 40000,
        document: "invoice_001.pdf",
        documentS3Key: "invoices/mock-inv-001.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "DRAFT",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },

  /* Draft contract financing — user chose new/existing contract */
  {
    id: "mock-draft-contract-1",
    type: "Contract financing",
    status: "draft",
    cardStatus: {
      badgeKey: "draft",
      displayLabel: "Draft",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: "Mining Rig Repair 12654",
    customer: "Beta Corp",
    applicationDate: "2026-03-09",
    contractValue: 250000,
    facilityApplied: 200000,
    approvedFacility: "N/A",
    updatedAt: "2026-03-09T14:00:00Z",
    invoices: [
      {
        id: "inv-mock-2",
        number: "INV-101",
        maturityDate: "2026-05-20",
        value: 75000,
        appliedFinancing: 60000,
        document: "invoice_101.pdf",
        documentS3Key: "invoices/mock-inv-101.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "DRAFT",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: "DRAFT",
  },

  /* Draft without financing structure — generic draft card, Continue Application only */
  {
    id: "mock-draft-generic-1",
    type: "Generic",
    status: "draft",
    cardStatus: {
      badgeKey: "draft",
      displayLabel: "Draft",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: null,
    customer: "—",
    applicationDate: "2026-03-10",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-10T09:00:00Z",
    invoices: [],
    contractStatus: null,
  },

  /* Under review — submitted, waiting for admin */
  {
    id: "mock-under-review-1",
    type: "Contract financing",
    status: "under_review",
    cardStatus: {
      badgeKey: "under_review",
      displayLabel: "Under Review",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: "Equipment Purchase Order",
    customer: "Delta Industries",
    applicationDate: "2026-03-05",
    contractValue: 400000,
    facilityApplied: 350000,
    approvedFacility: "N/A",
    updatedAt: "2026-03-08T11:00:00Z",
    invoices: [
      {
        id: "inv-mock-3",
        number: "INV-201",
        maturityDate: "2026-07-15",
        value: 120000,
        appliedFinancing: 96000,
        document: "invoice_201.pdf",
        documentS3Key: "invoices/mock-inv-201.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "SUBMITTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: "SUBMITTED",
  },

  /* Pending approval — similar to under review */
  {
    id: "mock-pending-approval-1",
    type: "Invoice financing",
    status: "submitted",
    cardStatus: {
      badgeKey: "submitted",
      displayLabel: "Submitted",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: null,
    customer: "Gamma Ltd",
    applicationDate: "2026-03-07",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-09T16:00:00Z",
    invoices: [
      {
        id: "inv-mock-4",
        number: "INV-301",
        maturityDate: "2026-06-01",
        value: 80000,
        appliedFinancing: 64000,
        document: "invoice_301.pdf",
        documentS3Key: "invoices/mock-inv-301.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "SUBMITTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },

  /* Pending amendment — action required from issuer */
  {
    id: "mock-pending-amendment-1",
    type: "Invoice financing",
    status: "pending_amendment",
    cardStatus: {
      badgeKey: "pending_amendment",
      displayLabel: "Action Required",
      showReviewOffer: false,
      showMakeAmendments: true,
    },
    contractTitle: null,
    customer: "Epsilon Co",
    applicationDate: "2026-03-06",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-09T10:00:00Z",
    invoices: [
      {
        id: "inv-mock-5",
        number: "INV-401",
        maturityDate: "2026-08-01",
        value: 60000,
        appliedFinancing: 48000,
        document: "invoice_401.pdf",
        documentS3Key: "invoices/mock-inv-401.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "AMENDMENT_REQUESTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },

  /* Contract offer received — admin sent contract offer. Offer wording: "Offer Received". */
  {
    id: "mock-contract-offer-1",
    type: "Contract financing",
    status: "sent",
    cardStatus: {
      badgeKey: "sent",
      displayLabel: "Offer Received",
      showReviewOffer: true,
      showMakeAmendments: false,
    },
    contractTitle: "Supply Agreement 2026",
    customer: "Zeta Trading",
    applicationDate: "2026-03-01",
    contractValue: 500000,
    facilityApplied: 400000,
    approvedFacility: "RM 380,000.00",
    updatedAt: "2026-03-10T08:00:00Z",
    invoices: [
      {
        id: "inv-mock-6",
        number: "INV-501",
        maturityDate: "2026-09-15",
        value: 150000,
        appliedFinancing: 120000,
        document: "invoice_501.pdf",
        documentS3Key: "invoices/mock-inv-501.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "SUBMITTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: "SENT",
  },

  /* Invoice offer received — contract approved, invoice has offer. Offer wording: "Offer Received". */
  {
    id: "mock-invoice-offer-1",
    type: "Contract financing",
    status: "sent",
    cardStatus: {
      badgeKey: "sent",
      displayLabel: "Offer Received",
      showReviewOffer: true,
      showMakeAmendments: false,
    },
    contractTitle: "Service Contract A",
    customer: "Theta Inc",
    applicationDate: "2026-02-28",
    contractValue: 300000,
    facilityApplied: 250000,
    approvedFacility: "RM 250,000.00",
    updatedAt: "2026-03-10T12:00:00Z",
    invoices: [
      {
        id: "inv-mock-7",
        number: "INV-601",
        maturityDate: "2026-10-01",
        value: 100000,
        appliedFinancing: 80000,
        document: "invoice_601.pdf",
        documentS3Key: "invoices/mock-inv-601.pdf",
        financingOffered: "RM 76,000.00",
        profitRate: "8.5%",
        status: "SENT",
        offerStatus: "Offer received",
        canReviewOffer: true,
      },
    ],
    contractStatus: "APPROVED",
  },

  /* Offer accepted — contract/invoice already accepted */
  {
    id: "mock-offer-accepted-1",
    type: "Invoice financing",
    status: "accepted",
    cardStatus: {
      badgeKey: "accepted",
      displayLabel: "Approved",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: null,
    customer: "Kappa Sdn Bhd",
    applicationDate: "2026-02-15",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "RM 90,000.00",
    updatedAt: "2026-03-01T14:00:00Z",
    invoices: [
      {
        id: "inv-mock-9",
        number: "INV-801",
        maturityDate: "2026-12-01",
        value: 100000,
        appliedFinancing: 90000,
        document: "invoice_801.pdf",
        documentS3Key: "invoices/mock-inv-801.pdf",
        financingOffered: "RM 90,000.00",
        profitRate: "9%",
        status: "APPROVED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },

  /* Offer rejected */
  {
    id: "mock-offer-rejected-1",
    type: "Contract financing",
    status: "rejected",
    cardStatus: {
      badgeKey: "rejected",
      displayLabel: "Rejected",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: "Rejected Contract",
    customer: "Lambda Co",
    applicationDate: "2026-02-10",
    contractValue: 180000,
    facilityApplied: 140000,
    approvedFacility: "N/A",
    updatedAt: "2026-02-25T11:00:00Z",
    invoices: [],
    contractStatus: "REJECTED",
  },

  /* Multi-invoice aggregation — mixed statuses, card shows highest priority (Action Required) */
  {
    id: "mock-multi-invoice-1",
    type: "Invoice financing",
    status: "pending_amendment",
    cardStatus: {
      badgeKey: "pending_amendment",
      displayLabel: "Action Required",
      showReviewOffer: false,
      showMakeAmendments: true,
    },
    contractTitle: null,
    customer: "Nu Industries",
    applicationDate: "2026-03-08",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-10T09:00:00Z",
    invoices: [
      {
        id: "inv-mock-11",
        number: "INV-A01",
        maturityDate: "2026-06-01",
        value: 50000,
        appliedFinancing: 40000,
        document: "inv_a01.pdf",
        documentS3Key: "invoices/mock-inv-a01.pdf",
        financingOffered: "RM 38,000.00",
        profitRate: "7%",
        status: "APPROVED",
        offerStatus: null,
        canReviewOffer: false,
      },
      {
        id: "inv-mock-12",
        number: "INV-A02",
        maturityDate: "2026-07-15",
        value: 60000,
        appliedFinancing: 48000,
        document: "inv_a02.pdf",
        documentS3Key: "invoices/mock-inv-a02.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "SENT",
        offerStatus: "Offer received",
        canReviewOffer: true,
      },
      {
        id: "inv-mock-13",
        number: "INV-A03",
        maturityDate: "2026-08-20",
        value: 45000,
        appliedFinancing: 36000,
        document: "inv_a03.pdf",
        documentS3Key: "invoices/mock-inv-a03.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "AMENDMENT_REQUESTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },

  /* Retraction — offer_details removed (no offer badge, no review button) */
  {
    id: "mock-retraction-1",
    type: "Invoice financing",
    status: "submitted",
    cardStatus: {
      badgeKey: "submitted",
      displayLabel: "Submitted",
      showReviewOffer: false,
      showMakeAmendments: false,
    },
    contractTitle: null,
    customer: "Mu Corp",
    applicationDate: "2026-03-04",
    contractValue: null,
    facilityApplied: null,
    approvedFacility: "N/A",
    updatedAt: "2026-03-09T15:00:00Z",
    invoices: [
      {
        id: "inv-mock-10",
        number: "INV-901",
        maturityDate: "2026-07-20",
        value: 55000,
        appliedFinancing: 44000,
        document: "invoice_901.pdf",
        documentS3Key: "invoices/mock-inv-901.pdf",
        financingOffered: "—",
        profitRate: "—",
        status: "SUBMITTED",
        offerStatus: null,
        canReviewOffer: false,
      },
    ],
    contractStatus: null,
  },
];
