ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INVOICE_ACCEPTED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SIGNING_PENDING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CONTRACT_SIGNED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INVOICE_SIGNED';
