/**
 * SC ComRep RMO-P2P Reporting Manual, Appendix A: Country Name.
 * Names are taken from the published v1.0 document only.
 *
 * The published PDF/DOCX duplicates the first Appendix A page and then
 * jumps to Isle of Man / Uganda. Costa Rica–Ireland and Portugal–Tuvalu
 * (including Singapore, France, Germany, India, Indonesia) are not printed
 * in that copy. Those names are not invented here.
 */

export const SC_APPENDIX_A_COUNTRIES = [
  "AFGHANISTAN",
  "ÅLAND ISLANDS",
  "ALBANIA",
  "ALGERIA",
  "AMERICAN SAMOA",
  "ANDORRA",
  "ANGOLA",
  "ANGUILLA",
  "ANTARCTICA",
  "ANTIGUA AND BARBUDA",
  "ARGENTINA",
  "ARMENIA",
  "ARUBA",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIJAN",
  "BAHAMAS",
  "BAHRAIN",
  "BANGLADESH",
  "BARBADOS",
  "BELARUS",
  "BELGIUM",
  "BELIZE",
  "BENIN",
  "BERMUDA",
  "BHUTAN",
  "BOLIVIA, PLURINATIONAL STATE OF",
  "BONAIRE, SINT EUSTATIUS AND SABA",
  "BOSNIA AND HERZEGOVINA",
  "BOTSWANA",
  "BOUVET ISLAND",
  "BRAZIL",
  "BRITISH INDIAN OCEAN TERRITORY",
  "BRUNEI DARUSSALAM",
  "BULGARIA",
  "BURKINA FASO",
  "BURUNDI",
  "CAMBODIA",
  "CAMEROON",
  "CANADA",
  "CAPE VERDE",
  "CAYMAN ISLANDS",
  "CENTRAL AFRICAN REPUBLIC",
  "CHAD",
  "CHILE",
  "CHINA",
  "CHRISTMAS ISLAND",
  "COCOS (KEELING) ISLANDS",
  "COLOMBIA",
  "COMOROS",
  "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
  "COOK ISLANDS",
  "ISLE OF MAN",
  "ISRAEL",
  "ITALY",
  "JAMAICA",
  "JAPAN",
  "JERSEY",
  "JORDAN",
  "KAZAKHSTAN",
  "KENYA",
  "KIRIBATI",
  "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  "KOREA, REPUBLIC OF",
  "KUWAIT",
  "KYRGYZSTAN",
  "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  "LATVIA",
  "LEBANON",
  "LESOTHO",
  "LIBERIA",
  "LIBYAN ARAB JAMAHIRIYA",
  "LIECHTENSTEIN",
  "LITHUANIA",
  "LUXEMBOURG",
  "MACAO",
  "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
  "MADAGASCAR",
  "MALAWI",
  "MALAYSIA",
  "MALDIVES",
  "MALI",
  "MALTA",
  "MARSHALL ISLANDS",
  "MARTINIQUE",
  "MAURITANIA",
  "MAURITIUS",
  "MAYOTTE",
  "MEXICO",
  "MICRONESIA, FEDERATED STATES OF",
  "MOLDOVA, REPUBLIC OF",
  "MONACO",
  "MONGOLIA",
  "MONTENEGRO",
  "MONTSERRAT",
  "MOROCCO",
  "MOZAMBIQUE",
  "MYANMAR",
  "NAMIBIA",
  "NAURU",
  "NEPAL",
  "NETHERLANDS",
  "NEW CALEDONIA",
  "NEW ZEALAND",
  "NICARAGUA",
  "NIGER",
  "NIGERIA",
  "NIUE",
  "NORFOLK ISLAND",
  "NORTHERN MARIANA ISLANDS",
  "NORWAY",
  "OMAN",
  "PAKISTAN",
  "PALAU",
  "PALESTINIAN TERRITORY, OCCUPIED",
  "PANAMA",
  "PAPUA NEW GUINEA",
  "PARAGUAY",
  "PERU",
  "PHILIPPINES",
  "PITCAIRN",
  "POLAND",
  "UGANDA",
  "UKRAINE",
  "UNITED ARAB EMIRATES",
  "UNITED KINGDOM",
  "UNITED STATES",
  "UNITED STATES MINOR OUTLYING ISLANDS",
  "URUGUAY",
  "UZBEKISTAN",
  "VANUATU",
  "VENEZUELA, BOLIVARIAN REPUBLIC OF",
  "VIET NAM",
  "VIRGIN ISLANDS, BRITISH",
  "VIRGIN ISLANDS, U.S.",
  "WALLIS AND FUTUNA",
  "WESTERN SAHARA",
  "YEMEN",
  "ZAMBIA",
  "ZIMBABWE",
] as const;

export type ScAppendixACountry = (typeof SC_APPENDIX_A_COUNTRIES)[number];

export function isScAppendixACountry(value: unknown): value is ScAppendixACountry {
  return typeof value === "string" && (SC_APPENDIX_A_COUNTRIES as readonly string[]).includes(value);
}

/** Keep a stored value visible even if it is not in the printed Appendix A page set. */
export function scAppendixASelectValues(current?: string | null): string[] {
  const list: string[] = [...SC_APPENDIX_A_COUNTRIES];
  const trimmed = current?.trim() ?? "";
  if (trimmed && !list.includes(trimmed)) list.unshift(trimmed);
  return list;
}
