import { PROSPECTUS_FIXED_SHARIAH_PRINCIPLE } from "@cashsouk/types";
import {
  HIBAH_ACTING_THROUGH,
  HIBAH_GRANTOR,
  SETTLEMENT_CONFIRMATION_COPY,
  type SettlementHibahReceiptSnapshot,
} from "./types";

export function sampleSettlementHibahReceiptSnapshot(
  overrides: Partial<SettlementHibahReceiptSnapshot> = {}
): SettlementHibahReceiptSnapshot {
  return {
    templateId: "settlement-hibah-receipt-issuer-v1",
    templateVersion: "V01",
    snapshotGeneratedAt: "2026-09-02T03:00:00.000Z",
    snapshotSha256: "abc",
    source: "SETTLEMENT_COMPLETED",
    receiptNumber: "SET-ARF-202608-A52",
    version: "V01",
    receiptDate: "2026-09-02T03:00:00.000Z",
    receiptDateDisplay: "02 Sep 2026",
    settlementId: "set-1",
    settlementReference: "SET-ARF-202608-A52",
    noteId: "note-1",
    noteReference: "ARF-202608-A52",
    facilityReference: "FAC-1",
    issuerReference: "ISS-1",
    issuerLegalName: "Helios Sdn Bhd",
    issuerCompanyNumber: "1234567-A",
    paymasterName: "Paymaster Co",
    invoiceNumber: "INV-9",
    invoiceFaceValue: 100_000,
    maturityDate: "2026-11-30T00:00:00.000Z",
    maturityDateDisplay: "30 Nov 2026",
    clearedValueDate: "2026-08-15T00:00:00.000Z",
    clearedValueDateDisplay: "15 Aug 2026",
    clearedValueDateSource: "ACTUAL_SETTLEMENT_DATE",
    paymentDate: "2026-08-15T00:00:00.000Z",
    paymentDateDisplay: "15 Aug 2026",
    paymentReference: "BANK-REF-1",
    settlementStatus: "Fully settled",
    grossReceiptAmount: 105_000,
    investorPrincipal: 100_000,
    investorProfitGross: 3_000,
    unpaidContractualFees: 0,
    tawidhAmount: 200,
    gharamahAmount: 50,
    priorPaymentsCredits: 0,
    totalApplied: 103_250,
    hibahAmount: 1_750,
    totalAllocated: 105_000,
    unallocatedBalance: 0,
    investorScheduleReference: "IS-ARF-202608-A52-V01",
    hibahGrantor: HIBAH_GRANTOR,
    hibahRecipient: "Helios Sdn Bhd",
    actingThrough: HIBAH_ACTING_THROUGH,
    shariahStructure: PROSPECTUS_FIXED_SHARIAH_PRINCIPLE,
    confirmationCopy: SETTLEMENT_CONFIRMATION_COPY,
    authorisation: {
      stampSource: "SHARED_CERTIFICATE_STAMP",
      companyStamp: null,
    },
    ...overrides,
  };
}
