ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CONTRACT_PENDING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CONTRACT_SENT';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'CONTRACT_ACCEPTED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INVOICE_PENDING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INVOICES_SENT';
